# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiCertificate.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# را تغییر ندهید ui توجه:کد های مربوط به بخش
# برای تغییر مکان متن خط 340-350 را تغییر دهید(هر فانکشن مربوط به یک متن است)

from PIL import Image, ImageDraw, ImageFont
from bidi.algorithm import get_display
import textwrap
import arabic_reshaper
from openpyxl import Workbook,  load_workbook
from openpyxl_image_loader import SheetImageLoader

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import sys
# ? ------------------------------
# !add variables(images,fonts,excel)
img_certificate_path = 'blankCertificate.jpg'
# font_path = "B-NAZANIN.TTF"
myFont = ImageFont.truetype(".//B-NAZANIN.TTF", 49)
myFont2 = ImageFont.truetype(".//B-NAZANIN.TTF", 38)
myFont3 = ImageFont.truetype(".//B-NAZANIN.TTF", 33)
excel_path = 'لیست نفرات سهند.xlsx'

#! adding images


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 492)
        MainWindow.setStyleSheet("background-color: rgb(81, 81, 81);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_1.setGeometry(QtCore.QRect(460, 20, 91, 20))
        self.lbl_1.setStyleSheet("color: rgb(227, 227, 227);")
        self.lbl_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_1.setObjectName("lbl_1")
        self.lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_2.setGeometry(QtCore.QRect(460, 80, 91, 20))
        self.lbl_2.setStyleSheet("color: rgb(227, 227, 227);")
        self.lbl_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_2.setObjectName("lbl_2")
        self.lbl_3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_3.setGeometry(QtCore.QRect(450, 140, 91, 20))
        self.lbl_3.setStyleSheet("color: rgb(227, 227, 227);")
        self.lbl_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_3.setObjectName("lbl_3")
        self.lbl_4 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_4.setGeometry(QtCore.QRect(450, 170, 91, 20))
        self.lbl_4.setStyleSheet("color: rgb(227, 227, 227);")
        self.lbl_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_4.setObjectName("lbl_4")
        self.input_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_1.setGeometry(QtCore.QRect(180, 20, 289, 31))
        self.input_1.setStyleSheet("border-radius:5px;\n"
                                   "background-color: rgb(223, 223, 223);")
        self.input_1.setText("")
        self.input_1.setObjectName("input_1")
        self.input_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_2.setGeometry(QtCore.QRect(180, 80, 289, 31))
        self.input_2.setStyleSheet("border-radius:5px;\n"
                                   "background-color: rgb(223, 223, 223);")
        self.input_2.setText("")
        self.input_2.setObjectName("input_2")
        self.input_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_3.setGeometry(QtCore.QRect(300, 140, 151, 21))
        self.input_3.setStyleSheet("border-radius:5px;\n"
                                   "background-color: rgb(223, 223, 223);")
        self.input_3.setText("")
        self.input_3.setObjectName("input_3")
        self.input_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_4.setGeometry(QtCore.QRect(300, 170, 151, 21))
        self.input_4.setStyleSheet("border-radius:5px;\n"
                                   "background-color: rgb(223, 223, 223);")
        self.input_4.setText("")

        self.input_4.setObjectName("input_4")
        self.lbl_5 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_5.setGeometry(QtCore.QRect(470, 300, 91, 20))
        self.lbl_5.setStyleSheet("color: rgb(227, 227, 227);")
        self.lbl_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_5.setObjectName("lbl_5")
        self.btn_browse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_browse.setGeometry(QtCore.QRect(30, 300, 75, 31))
        self.btn_browse.setStyleSheet("\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(19, 121, 255);\n"
                                      "border-radius:5px")
        self.btn_browse.setObjectName("btn_browse")
        self.input_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_5.setGeometry(QtCore.QRect(120, 300, 351, 31))
        self.input_5.setStyleSheet("border-radius:5px;\n"
                                   "background-color: rgb(223, 223, 223);")
        self.input_5.setText("")
        self.input_5.setObjectName("input_5")
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(250, 390, 75, 31))
        self.btn_run.setStyleSheet("\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(19, 121, 255);\n"
                                   "border-radius:5px")
        self.btn_run.setObjectName("btn_run")
        self.btn_img = QtWidgets.QPushButton(self.centralwidget)
        self.btn_img.setGeometry(QtCore.QRect(30, 350, 75, 31))
        self.btn_img.setStyleSheet("\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "background-color: rgb(19, 121, 255);\n"
                                   "border-radius:5px")
        self.btn_img.setObjectName("btn_browse_3")
        self.lbl_6 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_6.setGeometry(QtCore.QRect(470, 350, 91, 20))
        self.lbl_6.setStyleSheet("color: rgb(227, 227, 227);")
        self.lbl_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_6.setObjectName("lbl_6")
        self.input_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_6.setGeometry(QtCore.QRect(120, 350, 351, 31))
        self.input_6.setStyleSheet("border-radius:5px;\n"
                                   "background-color: rgb(223, 223, 223);")
        self.input_6.setText("")
        self.input_6.setObjectName("input_6")
        self.input_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_7.setGeometry(QtCore.QRect(300, 200, 151, 21))
        self.input_7.setStyleSheet("border-radius:5px;\n"
                                   "background-color: rgb(223, 223, 223);")
        self.input_7.setText('')
        self.input_7.setObjectName("input_7")
        # --------------
        self.input_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_8.setGeometry(QtCore.QRect(300, 230, 151, 21))
        self.input_8.setStyleSheet("border-radius:5px;\n"
                                   "background-color: rgb(223, 223, 223);")
        self.input_8.setText('')
        self.input_8.setObjectName("input_8")
        self.lbl_7 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_7.setGeometry(QtCore.QRect(450, 200, 91, 20))
        self.lbl_7.setStyleSheet("color: rgb(227, 227, 227);")
        self.lbl_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_7.setObjectName("lbl_7")
        # --------------
        self.lbl_8 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_8.setGeometry(QtCore.QRect(450, 230, 91, 20))
        self.lbl_8.setStyleSheet("color: rgb(227, 227, 227);")
        self.lbl_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_8.setObjectName("lbl_8")
        # ---------------
        self.lbl_9 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_9.setGeometry(QtCore.QRect(10, 455, 91, 20))
        self.lbl_9.setStyleSheet("color: rgb(227, 227, 227);")
        self.lbl_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_9.setObjectName("lbl_9")
        # ---------------
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 579, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
# *atributes are here
        self.course = ''
        self.duration = ''
        self.start_date = ''
        self.end_date = ''
        self.course_number = ''
# *connections are here
        self.btn_browse.clicked.connect(self.excel_browse)
        self.btn_img.clicked.connect(self.img_browse)
        self.btn_run.clicked.connect(self.run)
# *methods are here

    def excel_browse(self):
        global excel_path
        excel_path = QFileDialog.getOpenFileName(
            None, 'open file', '', 'All files(*);;Excel files(*.xlsx)')
        if excel_path:
            self.input_5.setText(str(excel_path[0]))
            excel_path = excel_path[0]

    def img_browse(self):
        global img_path
        img_path = QFileDialog.getOpenFileName(
            None, 'open file', '', 'All files(*);;Png files(*.png);;JPG files(*.jpg)')
        if img_path:
            self.input_6.setText(img_path[0])
            img_path = img_path[0]

    def font_browse(self):
        font_path = QFileDialog.getOpenFileName(
            None, 'open file', '', 'All files(*);;TTF files(*.TTF);;')
        return font_path

    def run(self):
        self.course = self.input_1.text()
        self.duration = self.input_2.text()
        self.start_date = self.input_3.text()
        self.end_date = self.input_4.text()
        self.course_number = self.input_7.text()
        self.make_date = self.input_8.text()
        self.save_path = str(QFileDialog.getExistingDirectory(None))

        main_function(self.course, self.duration,
                      self.start_date, self.end_date, self.make_date, self.course_number, self.save_path, excel_path, img_path)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "نرم افزار صدور مدرک"))
        self.lbl_1.setText(_translate("MainWindow", "نام دوره"))
        self.lbl_2.setText(_translate("MainWindow", "مدت زمان"))
        self.lbl_3.setText(_translate("MainWindow", "تاریخ شروع"))
        self.lbl_4.setText(_translate("MainWindow", "تاریخ اتمام"))
        self.lbl_5.setText(_translate("MainWindow", "فایل اکسل"))
        self.btn_browse.setText(_translate("MainWindow", "browse"))
        self.btn_run.setText(_translate("MainWindow", "Run"))
        self.btn_img.setText(_translate("MainWindow", "Browse"))
        self.lbl_6.setText(_translate("MainWindow", "قالب مدرک"))
        self.lbl_7.setText(_translate("MainWindow", "شماره دوره"))
        self.lbl_8.setText(_translate("MainWindow", 'تاریخ صدور'))
        self.lbl_9.setText(_translate("MainWindow", 'NG-سینا ابراهیمی'))


def meow(inp1, inp2, inp3, inp4, inp7):
    print(inp1, inp2, inp3, inp4, inp7)
    print('done')


def text_maker(text):
    correctText = arabic_reshaper.reshape(text)
    bidiText = get_display(correctText)
    return bidiText


def center_wrap(text, aptx, cwidth=80, **kw):
    lines = textwrap.wrap(text, width=112)
    lines_default = textwrap.wrap(aptx, width=112, fix_sentence_endings=True)
    max = len(lines_default)

    for line in lines_default:
        lines.append(line)

    return "\n\n\n".join(line.ljust(cwidth) for line in lines)


def main_function(course, duration, start_date, end_date, make_date, course_digit, save_p, excel_p, img_p):
    wb = load_workbook(excel_p)
    ws = wb.active
    image_column = ""
    image_loader = SheetImageLoader(ws)
    img_person = ''
    img_person_exist = None
    make_date = make_date
    codemelli = ''
    codemelli_exist = None
    codemelli_column = ''
    fname_lname = ''
    fname_lname_exist = None
    fname_lname_column = ''
    fathername = ''
    fathername_column = ''
    fathername_exist = None
    course = course
    duration = duration
    date1 = start_date
    date1_column = ''
    date2 = end_date
    date1_exist = None
    cr_digit = ''
    i = 1
    for cell in ws[1]:
        if cell.value == 'شماره ملی':
            # finds codemelli column letter
            # پیدا کردن شماره ستون کد ملی
            codemelli_column = cell.column_letter
            print('code col found')
        if cell.value == 'نام و نام خانوادگی':
            # پیدا کردن شماره ستون نام و نام خانوادگی
            fname_lname_column = cell.column_letter
            print('name col found')

        if cell.value == 'عکس4*3':
            # پیدا کردن شماره ستون عکس
            image_column = cell.column_letter
            print('img col found')
        if cell.value == 'نام پدر':
            fathername_column = cell.column_letter
        if cell.value == 'تاریخ برگزاری':
            date1_column = cell.column_letter

    for row in range(2, ws.max_row + 1):
        # iterate all rows to max row anc checks the code melli column
        img_certificate_pil = Image.open(img_p)
        img_certificate_pil_duplicate = img_certificate_pil
        if ws[f'{codemelli_column}{row}'].value == None:
            codemelli_exist = False
            pass
        else:
            # gets the code melli
            codemelli = ws[f'{codemelli_column}{row}'].value
            codemelli_exist = True
            print('we have code', f'{codemelli_column}{row}')
            print('------------')
        if ws[f'{fathername_column}{row}'].value == None:
            fathername_exist = False
        else:
            fathername = ws[f'{fathername_column}{row}'].value
            print('we have father name at', f'{fathername_column}{row}')
            # gets father name
            print('------------')
        if ws[f'{date1_column}{row}'].value == None:
            date1_exist = False
        else:
            date1 = ws[f'{date1_column}{row}'].value
            # gets date
            print('we have date', f'{date1}{row}')
            print('------------')
        if ws[f'{fname_lname_column}{row}'].value == None:
            fname_lname_exist = False
            pass
        else:
            # gets the name and last name
            fname_lname = ws[f'{fname_lname_column}{row}'].value
            fname_lname_exist = True
            print('we have name', f'{fname_lname_column}{row}')
            print('------------')

        if image_loader.image_in(f'{image_column}{row}'):
            img_person = image_loader.get(f'{image_column}{row}')
            img_person = img_person.resize((300, 300))
            img_person_exist = True
            print('we have img', f'{image_column}{row}')
            print('------------')

        else:
            img_person_exist = False
        if (img_person_exist and fname_lname_exist) and codemelli_exist:

            img_certificate_pil_duplicate.paste(img_person, (240, 220))
            img_certificate_pil_duplicate = ImageDraw.Draw(
                img_certificate_pil_duplicate)
            text = " آقای"+' '+str(fname_lname)+' ' + 'فرزند'+' '+str(fathername) + ' '+"به شماره ملی"+' '+str(codemelli)+' '\
                "در دوره آموزشی"+' '+course+" "+"که به مدت" + \
                ' ' + duration+" "+"ساعت از تاریخ"
            text2 = ' ' + date1 + ' ' + 'تا تاریخ'+" "+date1+" " + \
                'براساس قرار داد منعقده و توسط این آموزشگاه برگزار شده است شرکت نموده اند' + \
                '.'
            text = text+text2

            text3 = "این گواهی صرفا به منزله حضور در دوره آموزشی بوده و مشمول مزایای گواهینامه های مهارت سازمان فنی و حرفه ای کشور نمی گردد"+'.'

            if i < 10:
                cr_digit = date1[2:4]+date1[5:7] + \
                    str(course_digit)+'0'+str(i)
            else:
                cr_digit = date1[2:4]+date1[5:7] + \
                    str(course_digit)+str(i)

            ctwrap_text = center_wrap(text, aptx=text3, cwidth=110)
            final_txt = text_maker(ctwrap_text)

            # مکان متن هارا در اینجا تغییر دهید
            # تاریخ
            img_certificate_pil_duplicate.text(
                (1848, 438), make_date, font=myFont2, fill=(0, 0, 0), align='center')
            # کد دوره
            img_certificate_pil_duplicate.text(
                (1900, 370), cr_digit, font=myFont3, fill=(0, 0, 0), align='center')
            # متن اصلی
            img_certificate_pil_duplicate.text(
                (230, 730), final_txt, font=myFont, fill=(0, 0, 0), align='right', stroke_width=1)

            # img_certificate_pil.save(f'img\\{fname_lname}.pdf')
            img_certificate_pil.save(f"{save_p}" + f"\{fname_lname}.pdf")

            # img_certificate_pil.show()
            i += 1
            # if i > 1:
            #     break


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
